name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 */18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: sghani001

      - name: Commit and Push Changes Directly to Main
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: Auto-update 3D profile and snake animations [skip ci]"
            git pull --rebase origin main
            git push origin main
          fi
