name: Update Profile Trophies

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  update-trophies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Trophies
        uses: soulteary/profile-trophy-action@v1.0.3
        with:
          username: sghani001
          theme: nord
          no-frame: true
          no-bg: true
          margin-w: 8
          column: 4
          file-name: trophy.svg

      - name: Commit and Push SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add trophy.svg
          git diff-index --quiet HEAD || git commit -m "chore: update profile trophies"
          git push
